# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: life_game_development
test:
  <<: *default
  database: life_game_test

production:
  <<: *default
  database: life_game_production
  username: life_game
  password: <%= ENV['LIFE_GAME_DATABASE_PASSWORD'] %>
